config/routes.rb
Dms4u::Application.routes.draw do

  root :to => 'dashboard#index'

  post "sign_in" => "authentication#login"

  get "sign_in" => "authentication#sign_in"

  post "new_user" => "authentication#register"

  get "account_settings" => "authentication#account_settings"

  put "account_settings" => "authentication#set_account_info"

  get "forgot_password" => "authentication#forgot_password"

  put "forgot_password" => "authentication#send_password_reset_instructions"

  get "password_reset" => "authentication#password_reset"

  put "password_reset" => "authentication#new_password"

  match 'sign_in' => 'authentication#sign_in'

  match 'sign_out' => 'authentication#sign_out'

  match 'change_password' => 'authentication#change_password'
  
  match 'new_user' => 'authentication#new_user'

  match 'forgot_password' => 'authentication#forgot_password'

  match 'password_sent' => 'authentication#password_sent'

  

end

app/models/account.rb
class Account < ActiveRecord::Base

	belongs_to :user
	belongs_to :workplace
	belongs_to :country
	belongs_to :status

	has_many :wp_transactions

	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i

	validates :username, :presence => true, :length => {:minimum => 8, :maximum => 25}, :uniqueness => true
	validates :password, :presence => true
	validates :email, :presence => true, :length => {:maximum => 200}, :uniqueness => true, :format => EMAIL_REGEX
	validates :email_password, :presence => true
end

app/models/bank.rb
class Bank < ActiveRecord::Base

	belongs_to :status

	validates :account_no, :presence => true, :length => {:maximum => 200}, :uniqueness => true
	validates :swift_code, :presence => true, :length => {:maximum => 200}
	validates :owner_name, :presence => true, :length => {:maximum => 200}
	validates :address, :presence => true, :length => {:maximum => 200}
	
end

app/models/bank_transaction.rb
class BankTransaction < ActiveRecord::Base

	belongs_to :user
	belongs_to :bank

	has_many :bank_transactions

	validates :amount, :presence => true
	validates :transaction_date, :presence => true

end

app/models/country.rb
class Country < ActiveRecord::Base

	has_many :accounts

	validates :name, :presence => true, :length => {:maximum => 50}, :uniqueness => true
	
end

app/models/log.rb
class Log < ActiveRecord::Base
	
	belongs_to :user

	validates :ip, :presence => true, :length => {:minimum => 7, :maximum => 15}
	
end

app/models/paypal.rb
class Paypal < ActiveRecord::Base

	belongs_to :status
	has_many :paypal_transactions

	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i

	validates :email, :presence => true, :length => {:maximum => 200}, :uniqueness => true, :format => EMAIL_REGEX
	validates :name, :presence => true, :length => {:maximum => 200}

end

app/models/paypal_transaction.rb
class PaypalTransaction < ActiveRecord::Base
	
	belongs_to :user
	belongs_to :paypal

	validates :amount, :presence => true
	validates :transaction_date, :presence => true
	
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	validates :standard, :presence => true
	validates :percent, :presence => true
end

app/models/position.rb
class Position < ActiveRecord::Base

	has_many :users

	validates :name, :presence => true, :length => {:maximum => 200}, :uniqueness => true

end

app/models/role.rb
class Role < ActiveRecord::Base

	has_many :users
	
	validates :name, :presence => true, :length => {:maximum => 25}, :uniqueness => true

end

app/models/status.rb
class Status < ActiveRecord::Base

	validates :name, :presence => true, :length => {:maximum => 10}
	
end

app/models/unit.rb
class Unit < ActiveRecord::Base

	has_many :users
	
	validates :name, :presence => true, :length => {:maximum => 25}, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessible :username, :password, :password_confirmation, :new_password, :new_password_confirmation, 
					:previous_username, :remember_me
	attr_accessor	:password, :password_confirmation, :new_password, :new_password_confirmation, 
					:previous_username, :remember_me
	before_save		:encrypt_password

	belongs_to :position
	belongs_to :role
	belongs_to :unit

	has_many :logs
	has_many :accounts
	has_many :paypal_transactions
	has_many :bank_transactions

	validates :username,		:presence => true, 
								:length => {:minimum => 8, :maximum => 25}, 
								:uniqueness => true
	validates :name, 			:presence => true
	validates :new_password,	:confirmation => { :if => Proc.new {|user| !user.new_password.nil? && !user.new_password.empty? } }
	validates :username,		:presence => { :if => Proc.new {|user| user.previous_username.nil? || user.username != user.previous_username} }
	validates :username,		:uniqueness => { :if => Proc.new {|user| user.previous_username.nil? || user.username != user.previous_username} }

	# def self.authenticate_by_email(email, password)
	# 	user = find_by_email(email)
	# 	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	# 		user
	# 	else
	# 		nil
	# 	end
	# end

	def initialize(attributes = {})
		super # must allow the active record to initialize!
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end

	def self.authenticate_by_username(username, password)
		user = find_by_username(username)
		if user && user.hashed_password == BCrypt::Engine.hash_secret(password, user.salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.hashed_password = BCrypt::Engine.hash_secret(password, salt)
		end
	end

end

app/models/workplace.rb
class Workplace < ActiveRecord::Base

	has_many :accounts
	
	validates :name, :presence => true, :length => {:maximum => 50}, :uniqueness => true

end

app/models/wp_transaction.rb
class WpTransaction < ActiveRecord::Base

	belongs_to :account

	validates :amount, :presence => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	layout 'admin'

	def index
		render 'list'
	end

	def list
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def show_field_error(model, field)
		s=""

		if !model.errors[field].empty?
			s =
			<<-EOHTML
				<div class="error_message">
				 	#{model.errors[field][0]}
				</div>
			EOHTML
		end

		s.html_safe
	end

	private

	def clear_password_reset(user)
		user.password_expires_after = nil
		user.password_reset_token = nil
	end

	def verify_new_password(passwords)
		result = true

		if passwords[:new_password].blank? || (passwords[:new_password] != passwords[:new_password_confirmation])
			result = false
		end

		result
	end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang='en'>
<head>
	<meta httpd-equiv='Content-Type' content='text/html; charset=utf-8'>
	<title>DMS4U | <%= @page_title || 'Public Area' %></title>
	<meta name='author' content='XiangJun Wang'>
	<%= stylesheet_link_tag('admin', :media => 'all') %>
</head>
<body>
	<div id='header'>
		<h1>DMS4U</h1>
	</div>

	<div id='main'>
		<div id='navigation'>
			<p>
				<% if current_user %>
					Logged in as <%= current_user.username %>.
					<%= link_to "Sign Out", sign_out_path %>
					 <%= link_to "Account Settings", account_settings_path %>
				<% else %>
					<%= link_to "Sign up", new_user_path %> or
					<%= link_to "Sign In", sign_in_path %>
				<% end %>
			</p>
		</div>
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>

		<div id='content'>
			<%= yield %>
		</div>
		<div class='clear'></div>
	</div>

	<div id='footer'>
		<p id='copyright'>&copy; Copyright 2014 </p>
	</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dms4u</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang='en'>
<head>
	<meta httpd-equiv='Content-Type' content='text/html; charset=utf-8'>
	<title>DMS4U | <%= @page_title || 'Public Area' %></title>
	<meta name='author' content='XiangJun Wang'>
	<%= stylesheet_link_tag('public', :media => 'all') %>
</head>
<body>
	<div id='header'>
		<h1>DMS4U</h1>
	</div>

	<div id='main'>
		<div id='navigation'>
		</div>
		<% if !flash[:notice].blank? %>
			<div class='notice'>
				<%= flash[:notice] %>
			</div>
		<% end %>

		<div id='content'>
			<%= yield %>
		</div>
		<div class='clear'></div>
	</div>

	<div id='footer'>
		<p id='copyright'>&copy; Copyright 2014 </p>
	</div>

</body>
</html>